routes/contratos.py
from flask import Blueprint,render_template, request, redirect, url_for, flash, session, make_response

from models.tipoPredio import TipoPredio
from models.ubigeo import Ubigeo
from models.predio import Predio
from models.area_comun import Area_Comun
from models.predio_area_comun import Predio_Area_Comun
from models.servicio import Servicio
from models.solicitudCotizacion import SolicitudCotizacion
from models.solicitud import Solicitud
from models.rol import Rol
from models.tipoDocumento import TipoDocumento
from models.persona import Persona
from models.personal import Personal
from models.solicitante import Solicitante
from models.contrato import Contrato
from datetime import datetime

from jinja2 import Environment, FileSystemLoader
import pdfkit
import webbrowser

from utils.clean_cache import borrar_cache
from utils.gen_route import route

import os
from datetime import datetime,timedelta

from Google.ObtenerTokens import obtener_token
from Google.Carpetas import crear_carpeta
from Google.DescargarArchivos import descargar_archivo
from Google.SubirArchivo import subir_archivo, reemplazar_archivo

from utils.db import db

routes = Blueprint("routes", __name__, url_prefix="/contratos")

@routes.route('/<tipo>/<id>', methods=['POST','GET'])
def contratos(tipo,id):
    borrar_cache(["Vacio.png"])
    
    id_personal = int(id)
    id_solicitante = int(id)
    cotizaciones = []
    
    if tipo == "personal" :
    
        cotizaciones = SolicitudCotizacion.query.filter(
            SolicitudCotizacion.id_personal == id_personal,
            ~SolicitudCotizacion.id_solicitud_cotizacion.in_(
                db.session.query(Contrato.id_solicitud_cotizacion)
            ),
            (SolicitudCotizacion.id_estado == 1) | 
            (SolicitudCotizacion.id_estado == None)
        ).all()
        
    if tipo == "solicitante":
        contratos_pendientes = Contrato.query.filter(
            Contrato.id_solicitante == id_solicitante,
            Contrato.fecha_contrato != None,
            Contrato.fecha_firma_solicitante == None,
            Contrato.fecha_firma_personal == None,
        ).all()
        contratos_registrados = Contrato.query.filter(
            Contrato.id_solicitante == id_solicitante,
            Contrato.fecha_contrato != None,
            Contrato.fecha_firma_solicitante != None,
            Contrato.fecha_firma_personal != None,
            Contrato.fecha_registro != None,
        ).all()
    else:
        contratos_pendientes = Contrato.query.filter(
            Contrato.id_personal == id_personal,
            Contrato.fecha_contrato != None,
            Contrato.fecha_firma_solicitante != None,
            Contrato.fecha_firma_personal == None,
        ).all()
        contratos_registrados = Contrato.query.filter(
            Contrato.id_personal == id_personal,
            Contrato.fecha_contrato != None,
            Contrato.fecha_firma_solicitante != None,
            Contrato.fecha_firma_personal != None,
            Contrato.fecha_registro != None,
        ).all()

    return render_template(
        'contratos.html',
        tipo = tipo,
        id=id,
        cotizaciones=cotizaciones,
        contratos_pendientes = contratos_pendientes,
        contratos_registrados = contratos_registrados
    )
        
        
@routes.route('/crear_contrato/<tipo>/<id>/<id_solicitud_cotizacion>', methods=['POST','GET'])
def crear_contrato(tipo,id,id_solicitud_cotizacion):
    cotizacion = SolicitudCotizacion.query.filter(
        SolicitudCotizacion.id_solicitud_cotizacion == id_solicitud_cotizacion
    ).all()
    
    solicitud = Solicitud.query.filter(
        Solicitud.id_solicitud == cotizacion[0].id_solicitud    
    ).all()
    
    id_personal = id
    id_solicitante = solicitud[0].id_solicitante
    
    fecha_actual = datetime.now().date()
    fecha_actual_str = fecha_actual.strftime("%Y-%m-%d")
    
    print("FECHAAAAAAAAAAA: ",fecha_actual)
    
    contrato = Contrato(id_solicitud_cotizacion,
                        id_personal,
                        id_solicitante,
                        fecha_actual_str, 
                        None,
                        None,
                        None,
                        None)
    db.session.add(contrato)
    db.session.commit()
    
    
    contrato_final = Contrato.query.filter(
        Contrato.id_solicitud_cotizacion == id_solicitud_cotizacion,
        Contrato.id_personal == id_personal,
        Contrato.id_solicitante == id_solicitante
    ).all()
    
    id_contrato = contrato_final[0].id_contrato
    
    crear_carpeta_contratos(id_contrato,id_solicitud_cotizacion,id_personal,id_solicitante)
    
    return redirect(url_for('routes.contratos', id=id, tipo = tipo))


def crear_carpeta_contratos(id_contrato,id_solicitud_cotizacion,id_personal,id_solicitante):
    nombre_carpeta = "contrato-"+str(id_contrato)+"-"+str(id_solicitud_cotizacion)+"-"+str(id_personal)+"-"+str(id_solicitante)    
    nombre_parent = "contratos"
     
    crear_carpeta(nombre_parent,nombre_carpeta)
    
    carpeta_datos_solicitante = ("datos_solicitante_"+nombre_carpeta)
    crear_carpeta(nombre_carpeta,carpeta_datos_solicitante)
    
    carpeta_datos_personal = ("datos_personal_"+nombre_carpeta)
    crear_carpeta(nombre_carpeta,carpeta_datos_personal)
    
    return 


@routes.route('/contrato/<accion>/<tipo>/<id>/<id_contrato>', methods=['POST','GET'])
def mostrar_contrato(accion,tipo,id,id_contrato):
    borrar_cache(["Vacio.png"])
    
    print("---------------------------------------------"+tipo,id,id_contrato)
    
    data = obtener_datos_contrato(id_contrato)
    
    data.update({
        'accion': accion,
        'tipo': tipo,
        'id': id,
        'id_contrato': id_contrato
    })

    
    return render_template('contrato.html', **data)
    
@routes.route('/firmar/<tipo>/<id>/<id_contrato>/<referencia>', methods=['POST','GET'])
def firmar_contrato(tipo,id,id_contrato,referencia):
    
    contrato = Contrato.query.get(id_contrato)
    
    fecha_actual = datetime.now().date()

    if tipo == "solicitante":
        contrato.fecha_firma_solicitante = fecha_actual
    else:
        contrato.fecha_firma_personal = fecha_actual  
        contrato.fecha_registro = fecha_actual 
        generar_pdf (id_contrato,tipo,referencia) 

    db.session.commit()
    
    flash("CONTRADO FIRMADO CORRECTAMENTE!!!")
    
    return redirect(url_for('routes.contratos', tipo = tipo, id = id)) 


def obtener_datos_contrato(id_contrato):
    contrato = Contrato.query.get(id_contrato)
    personal = Personal.query.get(contrato.id_personal)
    solicitante = Solicitante.query.get(contrato.id_solicitante)
    cotizacion = SolicitudCotizacion.query.get(contrato.id_solicitud_cotizacion)
    solicitud = Solicitud.query.get(cotizacion.id_solicitud)
    servicio = Servicio.query.get(solicitud.id_servicio)
    predio = Predio.query.get(solicitud.id_predio)
    ubigeo_predio = Ubigeo.query.get(predio.idubigeo)
    tipo_predio = TipoPredio.query.get(predio.id_tipo_predio)
    
    consulta_area_comun = db.session.query(Predio_Area_Comun, Area_Comun).join(Area_Comun, Predio_Area_Comun.id_area_comun == Area_Comun.id_area_comun)
    consulta_area_comun = consulta_area_comun.filter(Predio_Area_Comun.id_predio == predio.id_predio).all()

    predio_area_comun = []
    area_comun = []
    if len(consulta_area_comun) > 0:
        consulta = consulta_area_comun[0]
        predio_area_comun.append(consulta[0])
        area_comun.append(consulta[1])
        
    persona_personal = Persona.query.get(personal.id_persona)
    rol_personal = Rol.query.get(personal.id_rol)
    tipo_documento_personal = TipoDocumento.query.get(persona_personal.id_tipo_documento)
    
    persona_solicitante = Persona.query.get(solicitante.id_persona)
    rol_solicitante = Rol.query.get(solicitante.id_rol)
    tipo_documento_solicitante = TipoDocumento.query.get(persona_solicitante.id_tipo_documento)
    
    referencia = str(id_contrato)+"-"+str(cotizacion.id_solicitud_cotizacion)+"-"+str(personal.id_personal)+"-"+str(solicitante.id_solicitante)  
    
    firma_solicitante_link, huella_solicitante_link, firma_personal_link, huella_personal_link = cargar_documentos(referencia)
    
    data = {
        'referencia': referencia,
        'contrato': contrato,
        'personal': personal,
        'solicitante': solicitante,
        'cotizacion': cotizacion,
        'solicitud': solicitud,
        'servicio': servicio,
        'predio': predio,
        'ubigeo_predio': ubigeo_predio,
        'tipo_predio': tipo_predio,
        'predio_area_comun': predio_area_comun,
        'area_comun': area_comun,
        'persona_personal': persona_personal,
        'rol_personal': rol_personal,
        'tipo_documento_personal': tipo_documento_personal,
        'persona_solicitante': persona_solicitante,
        'rol_solicitante': rol_solicitante,
        'tipo_documento_solicitante': tipo_documento_solicitante,
        'firma_solicitante_link': firma_solicitante_link,
        'huella_solicitante_link': huella_solicitante_link,
        'firma_personal_link': firma_personal_link,
        'huella_personal_link': huella_personal_link
    }
    
    return data

def generar_pdf (id_contrato,tipo,referencia):
    borrar_cache(["Vacio.png"])
    
    accion = "ver_contrato"
    
    data = obtener_datos_contrato(id_contrato)
    
    data.update({
        'accion': accion,
        'tipo': tipo,
        'id': id,
        'id_contrato': id_contrato
    })
    
    nombre_template = "partials/_contrato_partial.html"
    html = render_template(nombre_template, **data)
    
    
    print(html)
    
    opciones = {
        'enable-local-file-access': '',
        'page-size': 'A4',
        'margin-top': '10mm',
        'margin-right': '10mm',
        'margin-bottom': '10mm',
        'margin-left': '10mm',
    }
    
    nombre_contrato = "contrato-"+referencia+".pdf"
    ruta_destino = route("Desktop","")

routes/cotizaciones.py
from flask import Blueprint, render_template as rt, request, redirect, url_for
from models.solicitudCotizacion import SolicitudCotizacion
from models.solicitud import Solicitud
from models.predio import Predio
from models.solicitante import Solicitante
from models.personal import Personal
from models.estado import Estado
from models.servicio import Servicio  # Asegúrate de importar el modelo Servicio correctamente
from utils.db import db
from utils.id import formatear_id
from datetime import datetime

bp = Blueprint('cotizaciones', __name__, url_prefix="/cotizaciones")

@bp.route('/<id>/cotzac', methods=['POST','GET'])
def cotizaciones(id):
    # Obtener todas las solicitudes
    solicitudes = Solicitud.query.all()

    # Obtener todas las solicitudes con cotizaciones
    solicitudes_con_cotizaciones = SolicitudCotizacion.query.all()
    solicitudes_con_cotizaciones_ids = [cotizacion.id_solicitud for cotizacion in solicitudes_con_cotizaciones]
    
    # Obtener las solicitudes pendientes
    cotizaciones_pendientes = [solicitud for solicitud in solicitudes if solicitud.id_solicitud not in solicitudes_con_cotizaciones_ids]
    cotizaciones_completadas = SolicitudCotizacion.query.all()

    cotizaciones_pendientes = sorted(cotizaciones_pendientes, key=lambda solicitud: solicitud.id_solicitud)
    cotizaciones_completadas = sorted(cotizaciones_completadas, key=lambda solicitud: solicitud.id_solicitud)

    predios = Predio.query.all()
    predios_dict = {predio.id_predio: predio.descripcion for predio in predios}

    solicitantes = Solicitante.query.all()
    solicitantes_dict = {solicitante.id_solicitante: solicitante.nombre_completo for solicitante in solicitantes}

    servicios = Servicio.query.all()
    servicios_dict = {servicio.id_servicio: servicio.descripcion for servicio in servicios}

    personalAll = Personal.query.all()
    personal_dict = {personal.id_personal: personal.nombre_completo for personal in personalAll}
    
    estados = Estado.query.all()
    estado_dict = {estado.id_estado: estado.descripcion for estado in estados}

    for solicitudp in cotizaciones_pendientes:
        solicitudp.id_solicitud = formatear_id(solicitudp.id_solicitud)
        solicitudp.descripcion_predio = predios_dict.get(solicitudp.id_predio)
        solicitudp.nombre_solicitante = solicitantes_dict.get(solicitudp.id_solicitante)
        solicitudp.descripcion_servicio = servicios_dict.get(solicitudp.id_servicio)  # Obtener la descripción del servicio
    
    for solicitudc in cotizaciones_completadas:
        solicitudc.id_solicitud = formatear_id(solicitudc.id_solicitud)
        solicitudc.nombre_personal = personal_dict.get(solicitudc.id_personal)
        solicitudc.descripcion_estado = estado_dict.get(solicitudc.id_estado)
    bandera = ' '
    if request.method == "POST":
        bandera = request.form.get('btn-atras')
    return rt("cotizaciones.html", cotizaciones_pendientes=cotizaciones_pendientes, cotizaciones_completadas=cotizaciones_completadas, bandera=bandera, id = id)


@bp.route('/aceptar', methods=['POST'])
def aceptar():
    if request.method == "POST":
        #ID_SOLICITUD
        id_solicitud = request.form.get('aceptar__id_solicitud')
        solicitud = Solicitud.query.get(id_solicitud)
        servicio = Servicio.query.get(solicitud.id_servicio)
        estado = Estado.query.get(1)
        print("Aceptado: ",id_solicitud)
        #FECHA
        fecha_cotizacion = datetime.now().date()
        #ID_PERSONAL
        id_personal = 1
        #IMPORTE
        importe_total=0
        pago = {
            "adm": 500,
            "limp": 300,
            "jar": 300,
            "vig": 400,
        }
        if servicio.id_servicio == 1:
            total_adm = solicitud.cant_administracion*pago["adm"]
            total_lim = solicitud.cant_plimpieza*pago["limp"]
            total_jar = solicitud.cant_jardineria*pago["jar"]
            total_vig = solicitud.cant_vigilantes*pago["vig"]
            importe_total = total_adm+total_lim+total_jar+total_vig
        elif(servicio.id_servicio==2):
            total_lim = solicitud.cant_plimpieza*pago["limp"]
            importe_total = total_lim
        elif(servicio.id_servicio==3):
            total_jar = solicitud.cant_jardineria*pago["jar"]
            importe_total = total_jar
        elif(servicio.id_servicio==4):
            total_vig = solicitud.cant_vigilantes*pago["vig"]
            importe_total = total_vig
        new_solicitud_cotizacion = SolicitudCotizacion(id_solicitud,id_personal,fecha_cotizacion,importe_total,estado.id_estado)
        db.session.add(new_solicitud_cotizacion) # agregación
        db.session.commit() # confirmación
        return redirect(url_for('cotizaciones.cotizaciones'))

@bp.route('/rechazar', methods=['POST'])
def rechazar():
    if request.method == "POST":
        id_solicitud = request.form.get('rechazar__id_solicitud')
        print("Rechazado: ",id_solicitud)
        return redirect(url_for('cotizaciones.cotizaciones'))

routes/login.py
from flask import Blueprint, render_template as rt, request, url_for, redirect
from routes.contratos import borrar_cache

bp = Blueprint('index', __name__) #al llamar el blue print en base sería (NomreBP.FuncionAsociadaARuta)

@bp.route('/', methods=['GET', 'POST'])
def index(): #esta función debe coincidir con el url_for del html (base)
    borrar_cache(["Vacio.png"])
    if request.method == 'POST':
        email = request.form['email']
        password = request.form['password']

        data_prueba = {
            "antonytqm@gmail.com":{
                "password": "qwerty",
                "nombre": "Antony",
                "apellido": "Vargas",
                "cargo": "Contratista",
                "tipo": "personal",
                "id": "3"
            },
            "arnold8900@gmail.com":{
                "password": "qwerty",
                "nombre": "Arnold",
                "apellido": "Camacho",
                "cargo": "Admin",
                "tipo": "personal",
                "id": "1"
            },
            "luis@gmail.com":{
                "password": "qwerty",
                "nombre": "Luis",
                "apellido": "Jimenez",
                "cargo": "Pdte Junta Propietarios",
                "tipo": "solicitante",
                "id": "5"
            }
        }
        
        if email in data_prueba.keys():
            # Los datos coinciden, realizar acciones adicionales
            d_password = data_prueba.get(email).get("password")
            if password==d_password:
                print("Exito")
                id = data_prueba.get(email).get("id")
                tipo = data_prueba.get(email).get("tipo")
                print(url_for('principal.principal' ,tipo = tipo ,id = id))
                
                return redirect(url_for('principal.principal',tipo = tipo  , id = id))
            else:
                print("Fallo")
        else:
            # Los datos no coinciden, mostrar mensaje de error
            print("Fallo")
    return rt("index.html") #El rendertemplate siempre buscará el archivo en templates

routes/principal.py
from flask import Blueprint, render_template as rt
from utils.clean_cache import borrar_cache

bp = Blueprint('principal', __name__, url_prefix="/principal") #al llamar el blue print en base sería (NomreBP.FuncionAsociadaARuta)

@bp.route('/<tipo>/<id>')
def principal(id,tipo):
    borrar_cache(["Vacio.png"])
    return rt("principal.html",tipo = tipo, id = id)

templates/base-user.html
<!DOCTYPE html>
<html lang="es">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Condosa - {%block title%}{%endblock%}</title>
    <link rel="stylesheet"
    rel="stylesheet" href="{{url_for('static',filename="css/style.css")}}">
    <link rel="stylesheet"
    href="{{url_for('static',filename="css/components/nav.css")}}">
  </head>
  
  <body>
    <div class="fondo"></div>

    <header class="header">

      <div class="container">
        <div class="btn-menu">
          <label for="btn-menu">☰</label>
        </div>
        <div class="logo">
          <a class="logo" href="{{ url_for('index.index') }}">CONDOSA</a>
        </div>
        <nav class="menu">
          <a href="{{ url_for('principal.principal',tipo = tipo ,id = id) }}">Inicio</a>
          <a href="#">Nosotros</a>
          <a href="#">Blog</a>
          <a href="#">Contacto</a>
        </nav>
      </div>
    </header>

    <section>
      <div class="skewed"></div>
    </section>

    <!--	--------------->
    <input type="checkbox" id="btn-menu" />
    <div class="container-menu">
      <div class="cont-menu">
        <nav>
          <a href="#">Portafolio</a>
          <a href="#">Servicios</a>
          <a href="#">Suscribirse</a>
          <a href="#">Facebook</a>
          <a href="#">Youtube</a>
          <a href="#">Instagram</a>
        </nav>
        <label for="btn-menu">✖️</label>
      </div>
    </div>
    {% block content %}
    <!-- Aquí va el contenido específico de la plantilla hija -->
    {% endblock %}
  </body>
    <section>
      <div class="skewed"></div>
    </section>
  <footer>
    <p>&copy; 2023 CONDOSA. Todos los derechos reservados.</p>
  </footer>

 


</html>

templates/contratos.html
{% extends 'base-user.html' %}
{% block title %}Cotizaciones{% endblock %}


{% block content %}
    {% include "partials/_message.html" %}

    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" href="{{url_for('static',filename='css/components/cotizaciones.css')}}">

   

    <div class="content-cuadro">
        <div class="cuadro">
            <!-- Titulo -->
            <div>
                <h1 class="titulo">Contratos</h1>
            </div>

            <!-- Pestañas -->
            <div class="tabs">
                <ul>
                    {% if tipo == "personal" %}
                        <li class="option option-active" id="crear-tab" onclick="mostrarTabla('crear')">
                            Crear Contratos
                        </li>
                        <li class="option" id="pendientes-tab" onclick="mostrarTabla('pendientes')" >
                            Contratos Pendientes
                        </li>
                        <li class="option option-desactive" id="registrados-tab" onclick="mostrarTabla('registrados')" >
                            Contratos Registrados
                        </li>
                    {% else %}
                        <li class="option option-active" id="pendientes-tab" onclick="mostrarTabla('pendientes')" >
                            Contratos Pendientes
                        </li>
                        <li class="option " id="registrados-tab" onclick="mostrarTabla('registrados')" >
                            Contratos Registrados
                        </li>
                    {% endif %}
                </ul>
            </div>

            {% if tipo == "personal" %}
                <!-- Tabla de CREAR-->
                <div id="tabla-crear" class="tabla-cotizaciones">
                    <table class="table is-bordered is-hoverable is-dark has-text-white">
                        <thead>
                            <tr>
                                <th>ID Cotizacion</th>
                                <th>Fecha Cotizacion</th>
                                <th>Importe</th>
                                <th>Crear</th>
                            </tr>
                        </thead>
                        <tbody>                    
                            {% for cotizacion in cotizaciones %}
                            <tr>
                                <td>{{cotizacion.id_solicitud_cotizacion}}</td>
                                <td>{{cotizacion.fecha_cotizacion}}</td>
                                <td>S/.{{cotizacion.importe}}</td>
                                <td>
                                    <a 
                                        href="{{url_for('routes.crear_contrato',tipo = tipo, id = id, id_solicitud_cotizacion = cotizacion.id_solicitud_cotizacion)}}" 
                                        method="POST"
                                        class="button" data-toggle="tooltip" title="Crear">
                                        <img class="tabla-icon" src=" {{ url_for('static',filename='img/crear_contrato.png') }} ">
                                    </a>
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
                    








                <!-- Tabla de FIRMAR -->
                <div id="tabla-pendientes" class="tabla-cotizaciones" style="display: none;">
                    <table class="table is-bordered is-hoverable">
                        <thead>
                            <tr>
                                <th>ID Contrato</th>
                                <th>ID Cotizacion</th>
                                <th>F. Creacion</th>
                                <th>F Firma Soli.</th>
                                <th>Accion</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for contrato in contratos_pendientes %}
                            <tr>
                                <td>{{contrato.id_contrato}}</td>
                                <td>{{contrato.id_solicitud_cotizacion}}</td>
                                <td>{{contrato.fecha_contrato}}</td>
                                <td>{{contrato.fecha_firma_solicitante}}</td>
                                <td>
                                    <a 
                                        href="{{url_for('routes.mostrar_contrato',accion = "firmar", tipo = tipo, id = id,id_contrato = contrato.id_contrato)}}" 
                                        method="POST"
                                        class="button" data-toggle="tooltip" 
                                        title="Firmar">
                                        <img class="tabla-icon" src=" {{ url_for('static',filename='img/firmar_contrato.png') }} ">
                                    </a>
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>











                <!-- Tabla de REGISTRADOS -->
                <div id="tabla-registrados" class="tabla-cotizaciones" style="display: none;">
                    <table class="table is-bordered is-hoverable">
                        <thead>
                            <tr>
                                <th>ID Contrato</th>
                                <th>ID Personal</th>
                                <th>ID Solicitante</th>
                                <th>F Registro</th>
                                <th>Accion</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for contrato in contratos_registrados%}
                            <tr>
                                <td>{{contrato.id_contrato}}</td>
                                <td>{{contrato.id_personal}}</td>
                                <td>{{contrato.id_solicitante}}</td>
                                <td>{{contrato.fecha_registro}}</td>
                                <td>
                                    <a 
                                        href="{{url_for('routes.mostrar_contrato',accion = "ver_contrato", tipo = tipo, id = id,id_contrato = contrato.id_contrato)}}" 
                                        method="POST"
                                        class="button" data-toggle="tooltip" 
                                        title="Firmar">
                                        <img class="tabla-icon" src=" {{ url_for('static',filename='img/ojo.png') }} ">
                                    </a>
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>

                <script src="{{ url_for('static', filename='js/contratos_personal.js') }}"></script>
            {% else %}
                <!-- Tabla de FIRMAR -->
                <div id="tabla-pendientes" class="tabla-cotizaciones">
                    <table class="table is-bordered is-hoverable is-dark has-text-white">
                        <thead>
                            <tr>
                                <th>ID Contrato</th>
                                <th>ID Cotizacion</th>
                                <th>F. Creacion</th>
                                <th>Acciones</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for contrato in contratos_pendientes %}
                            <tr>
                                <td>{{contrato.id_contrato}}</td>
                                <td>{{contrato.id_solicitud_cotizacion}}</td>
                                <td>{{contrato.fecha_contrato}}</td>
                                <td>
                                    <a  
                                        href="{{url_for('routes.mostrar_contrato',accion = "firmar", tipo = tipo, id = id,id_contrato = contrato.id_contrato)}}" 
                                        method="POST"
                                        class="button" data-toggle="tooltip" 
                                        title="Firmar">
                                        <img class="tabla-icon" src=" {{ url_for('static',filename='img/firmar_contrato.png') }} ">
                                    </a>
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>

                <!-- Tabla de REGISTRADOS -->
                <div id="tabla-registrados" class="tabla-cotizaciones" style="display: none;">
                    <table class="table is-bordered is-hoverable">
                        <thead>
                            <tr>
                                <th>ID Contrato</th>
                                <th>ID Personal</th>
                                <th>ID Solicitante</th>
                                <th>F Registro</th>
                                <th>Accion</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for contrato in contratos_registrados%}
                            <tr>
                                <td>{{contrato.id_contrato}}</td>
                                <td>{{contrato.id_personal}}</td>
                                <td>{{contrato.id_solicitante}}</td>
                                <td>{{contrato.fecha_registro}}</td>
                                <td>
                                    <a 
                                        href="{{url_for('routes.mostrar_contrato',accion = "ver_contrato", tipo = tipo, id = id,id_contrato = contrato.id_contrato)}}" 
                                        method="POST"
                                        class="button" data-toggle="tooltip" 
                                        title="Firmar">
                                        <img class="tabla-icon" src=" {{ url_for('static',filename='img/ojo.png') }} ">
                                    </a>
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>

                <script src="{{ url_for('static', filename='js/contratos_solicitante.js') }}"></script>
            {% endif %}
            
        </div>
    </div>


{% endblock %}

templates/index.html
{%extends 'base.html'%}
{%block title%}Inicio sesión{%endblock%}
{%block content%}
<link rel="stylesheet" href="{{url_for('static',filename="css/components/forms/form_style.css")}}">
<link rel="stylesheet" href="{{url_for('static',filename="css/components/forms/button_style.css")}}">
<link rel="stylesheet" href="{{url_for('static',filename="css/components/login.css")}}">
    <div class="login-form">
        <form class="form" method="POST" action="{{ url_for('index.index') }}">
            <h3>INICIO DE SESIÓN</h3>
            <div class="textInput">
                <input type="text" name="email" required>
                <label class="input__lbl">
                    <span class="txt-lbl">Email</span>
                </label>
            </div>
            <div class="textInput">
                <input type="password" name="password" required>
                <label class="input__lbl">
                    <span class="txt-lbl">Contraseña</span>
                </label>
            </div>
            <div class="form-btn">
                <a href="#" onclick="submitForm()" class="btn-neon">
                    <span id="span1"></span>
                    <span id="span2"></span>
                    <span id="span3"></span>
                    <span id="span4"></span>
                    Ingresar
                </a>
            </div>
        </form>
    </div>
<script>
    function submitForm() {
        document.querySelector('.form').submit();
    }
</script>
{%endblock%}